system_configuration:
    groups:
        diamante_desk_channels_email_group:
            title: 'Email'

    fields:
        diamante_email_processing.mailbox_server_address:
            data_type: string
            type: Symfony\Component\Form\Extension\Core\Type\TextType
            priority: 95
            options:
                label: 'Server Address'

        diamante_email_processing.mailbox_port:
            data_type: string
            type: Symfony\Component\Form\Extension\Core\Type\TextType
            priority: 90
            options:
                label: 'Port'
                tooltip: "It's typically on port 143. But IMAP over SSL is usually on port 993."

        diamante_email_processing.mailbox_ssl:
            data_type: boolean
            type: Symfony\Component\Form\Extension\Core\Type\ChoiceType
            priority: 85
            options:
                label: 'SSL'
                choices:
                    - No
                    - Yes

        diamante_email_processing.mailbox_username:
            data_type: string
            type: Symfony\Component\Form\Extension\Core\Type\TextType
            priority: 80
            options:
                label: 'Username'

        diamante_email_processing.mailbox_password:
            data_type: string
            type: Symfony\Component\Form\Extension\Core\Type\PasswordType
            priority: 75
            options:
                label: 'Password'

        diamante_email_processing.mailbox_delete_processed_messages:
            data_type: string
            type: Symfony\Component\Form\Extension\Core\Type\ChoiceType
            priority: 70
            options:
                label: 'Delete Processed Messages'
                tooltip: "Some IMAP servers do not allow copy/move operations on the messages. In this case they could be removed after processing."
                choices:
                    - No
                    - Yes

    tree:
        system_configuration:
            platform:
                children:
                    diamante_desk_setup:
                        children:
                            diamante_desk_channels:
                                children:
                                    diamante_desk_channels_email_group:
                                        priority: 260
                                        children:
                                            - diamante_email_processing.mailbox_server_address
                                            - diamante_email_processing.mailbox_port
                                            - diamante_email_processing.mailbox_ssl
                                            - diamante_email_processing.mailbox_username
                                            - diamante_email_processing.mailbox_password
                                            - diamante_email_processing.mailbox_delete_processed_messages
