language: php

php:
  - 7.0
  - 7.1
  - hhvm

sudo: false

matrix:
  allow_failures:
    - php: hhvm

branches:
  except:
  - l10n_master

before_install:
  - mysql -e 'create database diamantedesk;'
  - if [[ "$TRAVIS_PHP_VERSION"  = "hhvm" ]]; then cat travis.php.ini >> /etc/hhvm/php.ini ; fi
  - if [[ "$TRAVIS_PHP_VERSION" != "hhvm" ]]; then phpenv config-add travis.php.ini ; fi
  - composer self-update
  - composer global require "fxp/composer-asset-plugin:~1.2"

install:
  - composer install --prefer-source --profile --no-interaction

script: phpunit --version

after_script:

before_deploy:
  - rm -rf app/cache/*
  - rm -rf app/logs/*
  - zip -q -x \*.git* -x build/ -x travis.php.ini -x .travis.yml -r build/diamantedesk-application-full-$TRAVIS_TAG.zip .
  - tar --exclude=\*.git* --exclude=build --exclude=travis.php.ini --exclude=.travis.yml -zcf build/diamantedesk-application-full-$TRAVIS_TAG.tar.gz .

deploy:
  provider: releases
  api_key:
    secure: YKwIdKBgw+Je0MaizvarHIKai0+vuuNgIuyH5IV7xg9sDaFu5bQwFjZHocUEgOBS7mVxgSUnbmYvexQ4r92ryUGwAO/DfxI5WM9UWYBbl5ZuLa9TqFySkgu/U2/apGThUCJ5Dk1szr26LJ4swDRbcH919Dgdiw8zSxCSZSRkRQz6WFUYwPZTdoldjla/4KVGC3QhEOJZYjdoxxySXd5BneX1xmOGdR9AF6H1meZ8r6WOp5kyF81XpvZjNlaM30XnAD3r4Xm/YeLK+CxvpkHt1BcB2bQe4ojXV1EhdAdI7/jEC24g3ML3uhpYGCISskuaFSTdiJk/46PhYujBFYNynLee63KnRCvhe+CQvprxSiIvYrZw28q87tYqJ+HV2UbReOCxHJuMDAz2uAi7OQ2NQtrye37/y/Ct2qZBCYDWTsLxrozdy3/tXuWCVAyTXzU2LVGMyNXH7PHAhdYtgtoIEIlus3lr3btowEMxoXVjzStKfq9SqVt5HCDVgZxCm+rJJHjwyysKdJubVcEYr4KBYq8KZY/84ljorCgAlULEIHTr42IWprEoDX5M7sfFIC2qxKM9T4/keb51QtamM1InLBDAHvPmt6WOMMmRL7qESejT2BDMH4/DhNKX6SfYqEqbowgMJto60E3Nf5InZjb1XLfPKu1jSuwYCs8KTa57Apk=
  file:
    - build/diamantedesk-application-full-$TRAVIS_TAG.zip
    - build/diamantedesk-application-full-$TRAVIS_TAG.tar.gz
  skip_cleanup: true
  on:
    tags: true
    php: '7.1'
notifications:
  slack:
    secure: m50vDN3EBDOTuaakmieAnA/phVYbx+r9RlLItLgKiT1Y1+bYmqBqDJ/Uo2iXFumnGPQsan64nLI6mq9xaE3sCwaRYpNy3BPuOIJURe55Bnov5zaHwXl3c1ZSoSvfhJkfKniFSmo6gLSz+r4T2WwLwZKtHKEkiJ6mx9+DLMaal7fbe+fXFiejNjAqwZJ0/r8hTNkPMZUfuDRnlhAT4wijQbehFhhk0nZ0H+zY1yikrI7sO9a1KmBfWivnrGdN4s+svWj4jheIvQPSM022Xxr8z4bh09H5VJ4qrDl3S566QKP/Vn0bp15dLq/6YLZmIN5gCKof1FONwqirstvGwGaYWo1ea23vhJvG8uu1qs0KOXROzITWDVHTsqPqGriGUq4tGUPjNi2GR3ogMFQJmrdCru7SG8NaDP43N9nR1kC8vuG1HItivw+r9qOFWYFcnfBpPWi8Dyzsx4M+kiHKCZjkGhsWaAVs31Sd2Lhvh9JY7wu3eGRd+GiQDfTuiQ0mtQij3LlQDXg+fNtsiZHU7te4qAiQSODOvhjapTSNTl0iebbKLOTEwlf/rh4sy0k7ZeZu54TK/GjVCDcD0EkDWBG4uwjUOFRV+G0pmOEdYVlJzpbpibeaIKDpm577B8sdTjXL12Qpybyfov59W6oWn7lXG5nwnsh8RAXYB62qAE8FPt4=
