placeholders:
    page_title_after:
        items:
            default_branch_notification: ~

    view_content_data_additional_information:
        items:
            diamante_orouser_ticket_grid: ~
    pin_button:
        items:
            create_ticket_button:
                order: 200

items:
    default_branch_notification:
        template: DiamanteDeskBundle::defaultBranchNotification.html.twig
        applicable: @diamante.branch.placeholder->isDefault($entity$)
        data:
          default_branch: [entity]

    diamante_orouser_ticket_grid:
        template: DiamanteDeskBundle:OroUser:Grid.html.twig
        applicable: @oro_ui.placeholder.filter->isInstanceOf($entity$, %oro_user.entity.class%)
    create_ticket_button:
        template: DiamanteDeskBundle:Ticket:createButton.html.twig
