reports:
    tickets_by_priority:
        label: "Tickets by Priority"
        chart:
            type: grouped-line-chart
            x-axis: day
            y-axis:
              items:
                  - low
                  - medium
                  - high
        source:
            type: repository
            repository: "Diamante\\DeskBundle\\Infrastructure\\Persistence\\DoctrineReportRepository::getTicketsByPriority"

    tickets_by_priority_widget:
            label: "Tickets by Priority"
            chart:
                type: pie-chart
                label: priority
                data: value
            source:
                type: dql
                dql: "SELECT t.priority, count(t.priority) as value FROM Diamante\\DeskBundle\\Entity\\Ticket t group by t.priority"

    time_of_response:
        label: "Time of Response"
        chart:
            type: grouped-line-chart
            x-axis: day
            y-axis:
              items:
                  - 0-1
                  - 1-8
                  - 8-24
                  - more 24
        source:
            type: repository
            repository: "Diamante\\DeskBundle\\Infrastructure\\Persistence\\DoctrineReportRepository::getTimeOfResponseReportData"

    time_of_response_widget:
        label: "Time of Response"
        chart:
            type: bar-chart
            y-axis: data_count
            x-axis: data_range
        source:
            type: repository
            repository: "Diamante\\DeskBundle\\Infrastructure\\Persistence\\DoctrineReportRepository::getTimeOfResponseReportWidgetData"

    tickets_by_channels:
        label: "Tickets by Channels"
        chart:
            type: grouped-line-chart
            x-axis: day
            y-axis: data
            group: source
        source:
            type: dql
            dql: "select date(t.createdAt) as day, t.source as source, count(t.source) as data from Diamante\\DeskBundle\\Entity\\Ticket t GROUP BY t.source, day"

    tickets_by_channels_widget:
        label: "Tickets by Channels"
        chart:
            type: pie-chart
            label: label
            data: data
        source:
            type: dql
            dql: "select t.source as label, count(t.source) as data from  Diamante\\DeskBundle\\Entity\\Ticket t GROUP BY t.source"

    tickets_by_branches:
        label: "Tickets by Branches"
        chart:
            type: grouped-line-chart
            x-axis: day
            y-axis: data
            group: branch
        source:
            type: dql
            dql: "select date(t.createdAt) as day, b.name as branch, count(t.branch) as data from Diamante\\DeskBundle\\Entity\\Ticket t LEFT JOIN Diamante\\DeskBundle\\Entity\\Branch b WITH b.id = t.branch GROUP BY t.branch, day"

    tickets_by_branches_widget:
        label: "Tickets by Branches"
        chart:
            type: pie-chart
            label: branch
            data: data
        source:
            type: dql
            dql: "select b.name as branch, count(t.branch) as data from Diamante\\DeskBundle\\Entity\\Ticket t LEFT JOIN Diamante\\DeskBundle\\Entity\\Branch b WITH b.id = t.branch GROUP BY t.branch"

    ticket_timeline:
        label: "Ticket Timeline"
        chart:
            type: grouped-line-chart
            x-axis: day
            y-axis:
                items:
                    - new
                    - closed
                    - reopen
        source:
            type: dql
            dql: "select date(ttl.date) as day, sum(ttl.new), sum(ttl.closed), sum(ttl.reopen) from Diamante\\DeskBundle\\Entity\\TicketTimeline ttl GROUP BY day"
