config:
    map:
        '*':
            'oro/datagrid/action/delete-action': 'diamante/datagrid/action/delete-action'
            'orodatagrid/js/app/plugins/grid/floating-header-plugin': 'diamantedesk/js/app/plugins/grid/floating-header-plugin'
            'orodatagrid/js/app/components/datagrid-component': 'diamantedesk/js/app/components/datagrid-component'
            'oroform/js/app/views/wysiwig-editor/wysiwyg-editor-view': 'diamantedesk/js/app/views/wysiwig-editor/wysiwyg-editor-view'
        'diamante/datagrid/action/delete-action': 'oro/datagrid/action/delete-action'
        'diamantedesk/js/app/views/wysiwig-editor/wysiwyg-editor-view' :
            'oroform/js/app/views/wysiwig-editor/wysiwyg-editor-view' : 'oroform/js/app/views/wysiwig-editor/wysiwyg-editor-view'

    paths:
        'd3': 'bundles/diamantedesk/lib/d3/d3.min.js'
        'd3-tip' : 'bundles/diamantedesk/lib/d3-tip/index.js'
        'xregexp' : 'bundles/diamantedesk/lib/xregexp/xregexp-all.js'
        'diamante/attachments/draganddrop': 'bundles/diamantedesk/js/diam.attachments.js'
        'diamante/ajax.messages': 'bundles/diamantedesk/js/diam.ajax.messages.js'
        'diamante/palette': 'bundles/diamantedesk/js/palette.js'
        'diamante/datagrid/action/delete-action' : 'bundles/diamantedesk/js/datagrid/action/delete-action.js'
        'oroform/js/validator/regex' : 'bundles/diamantedesk/js/validator/regex.js'