diamante_front_bundle:
    resource:     "@DiamanteFrontBundle/Controller/IndexController.php"
    type:         annotation
    prefix:       /portal

diamante_front:
    path:         /portal

diamante_front_user:
    resource:     "@DiamanteFrontBundle/Controller/UserController.php"
    type:         rest
    prefix:       /portal

diamante_front_api_user:
    resource:     diamante.front.current_user.api.service_diamante
    type:         diamante_rest_service
    prefix:       /api/diamante/rest/{version}/desk/
    requirements:
        version:  latest|v1
        _format:  xml|json
    defaults:
        version:  latest
        _format:  json
