oro_menu_config:
    items:
        embedded_forms:
            label: 'oro.embeddedform.entity_plural_label'
            route: 'oro_embedded_form_list'
            extras:
                position:   20
                routes:     ['oro_embedded_form_*']
        diamante_branch_list:
            label: 'Branches'
            route: diamante_branch_list
            extras:
                routes: ['diamante_branch_*']
                position: 80
        diamante_ticket_list:
            label: 'All Tickets'
            route: diamante_ticket_list
            extras:
                routes: ['diamante_ticket_*', 'diamante_comment_*']
                position: 90
        diamante_report_list:
            label: 'Reports'
            uri: '#'
            extras:
                position: 95

        #reports
        diamante_report_tickets_by_priority:
            label: 'Tickets By priority'
            route: diamante_report_view
            routeParameters:
                id: 'tickets_by_priority'
            extras:
                routes: ['diamante_report_*']

        diamante_report_time_of_response:
            label: 'Time Of Response'
            route: diamante_report_view
            routeParameters:
                id: 'time_of_response'
            extras:
                routes: ['diamante_report_*']

        diamante_report_tickets_by_channels:
            label: 'Tickets by Channels'
            route: diamante_report_view
            routeParameters:
                id: 'tickets_by_channels'
            extras:
                routes: ['diamante_report_*']

        diamante_report_tickets_by_branch:
            label: 'Tickets by Branch'
            route: diamante_report_view
            routeParameters:
                id: 'tickets_by_branch'
            extras:
                routes: ['diamante_report_*']

        diamante_report_tickets_timeline:
            label: 'Tickets TimeLine'
            route: diamante_report_view
            routeParameters:
                id: 'tickets_timeline'
            extras:
                routes: ['diamante_report_*']

#        dashboard_tab:
#            display: false
        oro_calendar_view_default:
            display: false
        activities_tab:
            display: false
        reports_tab:
            display: false
        system_tab:
            display: false
        oro_platform_system_info:
            display: false
        diamante_config_tab:
          label: 'System'
          uri: '#'
          extras:
              position: 100
    tree:
        application_menu:
            children:
                diamante_branch_list: ~
                diamante_ticket_list: ~
                diamante_report_list:
                    children:
                        diamante_report_tickets_by_priority: ~
                        diamante_report_time_of_response: ~
                        diamante_report_tickets_by_channels: ~
                        diamante_report_tickets_by_branch: ~
                        diamante_report_tickets_timeline: ~
                diamante_config_tab:
                  children:
                    system_configuration: ~
                    users_management:
                      children:
                        user_list: ~
                        user_create: ~
                        user_groups: ~
                        user_roles: ~
                    integrations_submenu:
                      children:
                        embedded_forms: ~
                    oro_platform_system_info: ~
                    audit_list: ~



oro_titles:
    diamante_branch_list: ~
    diamante_branch_view: '%%branch.name%%'
    diamante_branch_create: 'Create Branch'
    diamante_branch_update: '%%branch.name%% - Edit'

    diamante_comment_create: 'Add Comment - %%ticket.subject%%'
    diamante_comment_update: 'Edit Comment - %%ticket.subject%%'

    diamante_ticket_list: ~
    diamante_ticket_view: '[%%ticket.key%%] %%ticket.subject%%'
    diamante_ticket_create: 'Create Ticket'
    diamante_ticket_update: '%%ticket.subject%% - Edit'
    diamante_ticket_create_attach: 'Add Attachment'

    diamante_report_view: '%%report.label%%'
