system_configuration:
    groups:
        diamantedesk_channels_front_group:
            title: 'Web'

    fields:
        diamante_front.registration_required:
            type: Symfony\Component\Form\Extension\Core\Type\ChoiceType
            data_type: boolean
            options:
                label: 'Registration Requied'
                choices:
                    - No
                    - Yes

        diamante_email_processing.mailbox_help:
            data_type: block
            type:  Diamante\EmailProcessingBundle\Form\Type\HelpChannelsConfigurationType

    tree:
        system_configuration:
            platform:
                children:
                    diamante_desk_setup:
                        children:
                            diamante_desk_channels:
                                children:
                                    diamantedesk_channels_front_group:
                                        priority: 160
                                        children:
                                            - diamante_front.registration_required
                                            - diamante_email_processing.mailbox_help